// <auto-generated />
using System;
using LimsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LimsApi.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    partial class LimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LimsApi.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganisationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatRegistration")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LimsApi.Models.ExtractionQC", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double?>("Concentration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GelResult")
                        .HasColumnType("text");

                    b.Property<bool>("Override")
                        .HasColumnType("boolean");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("QcMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("QubitConcentration")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ratio260230")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ratio260280")
                        .HasColumnType("double precision");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SampleId")
                        .IsUnique();

                    b.ToTable("ExtractionQCs");
                });

            modelBuilder.Entity("LimsApi.Models.Instrument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CalibrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("LimsApi.Models.InstrumentDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("InstrumentDocuments");
                });

            modelBuilder.Entity("LimsApi.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LimsApi.Models.MaintenanceLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompletedById");

                    b.HasIndex("InstrumentId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("LimsApi.Models.PurchaseOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("LimsApi.Models.ReferringPractitioner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ReferringPractitioners");
                });

            modelBuilder.Entity("LimsApi.Models.SOP", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActiveDocumentUrl")
                        .HasColumnType("text");

                    b.Property<string>("ArchivedDocumentUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingDocumentUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SOPs");
                });

            modelBuilder.Entity("LimsApi.Models.Sample", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AcceptanceStatus")
                        .HasColumnType("text");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CollectedBy")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateCollected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateReceivedInLab")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .HasColumnType("text");

                    b.Property<string>("ReferringPractitionerId")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .HasColumnType("text");

                    b.Property<string>("SampleKitId")
                        .HasColumnType("text");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SampleTypeEnum")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ReferringPractitionerId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("LimsApi.Models.SampleWorkflow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowSubType")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.ToTable("SampleWorkflows");
                });

            modelBuilder.Entity("LimsApi.Models.StockBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpenedById")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OpenedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("StockItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OpenedById");

                    b.HasIndex("StockItemId");

                    b.ToTable("StockBatches");
                });

            modelBuilder.Entity("LimsApi.Models.StockItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("LimsApi.Models.StockLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("StockBatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StockBatchId");

                    b.HasIndex("UserId");

                    b.ToTable("StockLogs");
                });

            modelBuilder.Entity("LimsApi.Models.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("LimsApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LimsApi.Models.WorkflowResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("ResultData")
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowSubType")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.ToTable("WorkflowResults");
                });

            modelBuilder.Entity("LimsApi.Models.WorkflowStockLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StockItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkflowSubType")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId");

                    b.ToTable("WorkflowStockLinks");
                });

            modelBuilder.Entity("LimsApi.Models.Worklist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InstrumentId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Worklists");
                });

            modelBuilder.Entity("LimsApi.Models.WorklistItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorklistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.HasIndex("WorklistId");

                    b.ToTable("WorklistItems");
                });

            modelBuilder.Entity("LimsApi.Models.ExtractionQC", b =>
                {
                    b.HasOne("LimsApi.Models.Sample", "Sample")
                        .WithOne("ExtractionQC")
                        .HasForeignKey("LimsApi.Models.ExtractionQC", "SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("LimsApi.Models.InstrumentDocument", b =>
                {
                    b.HasOne("LimsApi.Models.Instrument", "Instrument")
                        .WithMany("Documents")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("LimsApi.Models.Invoice", b =>
                {
                    b.HasOne("LimsApi.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LimsApi.Models.MaintenanceLog", b =>
                {
                    b.HasOne("LimsApi.Models.User", "CompletedBy")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("CompletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LimsApi.Models.Instrument", "Instrument")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedBy");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("LimsApi.Models.PurchaseOrder", b =>
                {
                    b.HasOne("LimsApi.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("LimsApi.Models.ReferringPractitioner", b =>
                {
                    b.HasOne("LimsApi.Models.Client", "Client")
                        .WithMany("ReferringPractitioners")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LimsApi.Models.Sample", b =>
                {
                    b.HasOne("LimsApi.Models.Client", "Client")
                        .WithMany("Samples")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LimsApi.Models.ReferringPractitioner", "ReferringPractitioner")
                        .WithMany("Samples")
                        .HasForeignKey("ReferringPractitionerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("ReferringPractitioner");
                });

            modelBuilder.Entity("LimsApi.Models.SampleWorkflow", b =>
                {
                    b.HasOne("LimsApi.Models.Sample", "Sample")
                        .WithMany("Workflows")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("LimsApi.Models.StockBatch", b =>
                {
                    b.HasOne("LimsApi.Models.User", "OpenedBy")
                        .WithMany("StockBatchesOpened")
                        .HasForeignKey("OpenedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LimsApi.Models.StockItem", "StockItem")
                        .WithMany("StockBatches")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpenedBy");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("LimsApi.Models.StockItem", b =>
                {
                    b.HasOne("LimsApi.Models.Supplier", "Supplier")
                        .WithMany("StockItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("LimsApi.Models.StockLog", b =>
                {
                    b.HasOne("LimsApi.Models.StockBatch", "StockBatch")
                        .WithMany("StockLogs")
                        .HasForeignKey("StockBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LimsApi.Models.User", "User")
                        .WithMany("StockLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockBatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LimsApi.Models.WorkflowResult", b =>
                {
                    b.HasOne("LimsApi.Models.Sample", "Sample")
                        .WithMany("WorkflowResults")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("LimsApi.Models.WorkflowStockLink", b =>
                {
                    b.HasOne("LimsApi.Models.StockItem", "StockItem")
                        .WithMany("WorkflowLinks")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("LimsApi.Models.Worklist", b =>
                {
                    b.HasOne("LimsApi.Models.User", "CreatedBy")
                        .WithMany("Worklists")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LimsApi.Models.Instrument", "Instrument")
                        .WithMany("Worklists")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("LimsApi.Models.WorklistItem", b =>
                {
                    b.HasOne("LimsApi.Models.Sample", "Sample")
                        .WithMany("WorklistItems")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LimsApi.Models.Worklist", "Worklist")
                        .WithMany("Items")
                        .HasForeignKey("WorklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");

                    b.Navigation("Worklist");
                });

            modelBuilder.Entity("LimsApi.Models.Client", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("ReferringPractitioners");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("LimsApi.Models.Instrument", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("Worklists");
                });

            modelBuilder.Entity("LimsApi.Models.ReferringPractitioner", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("LimsApi.Models.Sample", b =>
                {
                    b.Navigation("ExtractionQC");

                    b.Navigation("WorkflowResults");

                    b.Navigation("Workflows");

                    b.Navigation("WorklistItems");
                });

            modelBuilder.Entity("LimsApi.Models.StockBatch", b =>
                {
                    b.Navigation("StockLogs");
                });

            modelBuilder.Entity("LimsApi.Models.StockItem", b =>
                {
                    b.Navigation("StockBatches");

                    b.Navigation("WorkflowLinks");
                });

            modelBuilder.Entity("LimsApi.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");

                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("LimsApi.Models.User", b =>
                {
                    b.Navigation("MaintenanceLogs");

                    b.Navigation("StockBatchesOpened");

                    b.Navigation("StockLogs");

                    b.Navigation("Worklists");
                });

            modelBuilder.Entity("LimsApi.Models.Worklist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
